"""Added first and last names

Revision ID: 8a4d1a6c1473
Revises: 4866f8789275
Create Date: 2021-06-03 18:57:22.505745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4d1a6c1473'
down_revision = '4866f8789275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('person', sa.Column('last_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_person_first_name'), 'person', ['first_name'], unique=False)
    op.create_index(op.f('ix_person_last_name'), 'person', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_last_name'), table_name='person')
    op.drop_index(op.f('ix_person_first_name'), table_name='person')
    op.drop_column('person', 'last_name')
    op.drop_column('person', 'first_name')
    # ### end Alembic commands ###
